In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.21.0'

In [3]:
pd.__version__

'1.3.0'

In [4]:
df = pd.read_csv('data.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [5]:
df.shape

(11914, 16)

In [6]:
df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [7]:
df[df['Make']=='BMW']['MSRP'].sum()/ len(df[df['Make']=='BMW']['MSRP'])

61546.76347305389

In [8]:
df[df['Year']>=2015].isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [9]:
avg_hp = df[df['Year']>=2015]['Engine HP'].mean()

In [10]:
df['Engine HP'] = df['Engine HP'].fillna(avg_hp)

In [11]:
avg_hp_after_filling = df[df['Year']>=2015]['Engine HP'].mean()

In [12]:
round(avg_hp)

273

In [13]:
round(avg_hp_after_filling)

273

In [14]:
temp_df = df[df['Make'] == 'Rolls-Royce'][["Engine HP", "Engine Cylinders", "highway MPG"]]

In [15]:
temp_df.shape

(31, 3)

In [16]:
temp_df.drop_duplicates(keep='last', inplace = True)

In [17]:
temp_df.shape

(7, 3)

In [18]:
x = temp_df.values
x

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  20.],
       [563.,  12.,  21.],
       [453.,  12.,  19.],
       [322.,  12.,  15.],
       [624.,  12.,  21.]])

In [19]:
xtx = x.T @ x
xtx

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [20]:
xtx_inv = np.linalg.inv(xtx)
xtx_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [21]:
np.sum(xtx_inv)

0.032212320677486125

In [22]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [30]:
w = np.dot(np.dot(xtx_inv, x.T), y)

In [31]:
w

array([ -0.51945381, -30.99701027,  89.04312386])

In [26]:
xtx_inv.shape, x.T.shape, y.shape, w.shape

((3, 3), (3, 7), (7,), (3,))